# Generated by Django 3.0.2 on 2020-02-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200218_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
